package org.usfirst.frc.team1188.gamepad;

public enum AxisCode {
	LEFTSTICKX,
	LEFTSTICKY,
	RIGHTSTICKX,
	RIGHTSTICKY,
	LEFTTRIGGER,
	RIGHTTRIGGER,
	ELEVATORDOUBLEOVERRIDEUP,
	ELEVATORDOUBLEOVERRIDEDOWN,
	ARMDOUBLEOVERRIDEDOWN,
	ARMDOUBLEOVERRIDEUP
}
